# -*- coding: utf-8 -*-
"""workshopITbusinesSolutions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NtrJf3KoEqD3jsJg7hY1z9xL9RG0ebX6
"""

import requests
import pandas as pd
from bs4 import BeautifulSoup
from datetime import datetime

url = "https://en.wikipedia.org/wiki/List_of_Spotify_streaming_records"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers, timeout=20)
response.encoding = "utf-8"
soup = BeautifulSoup(response.text, "html.parser")

rows = []

tables = soup.select("table.wikitable")
table = None

for t in tables:
    header_cells = t.select("tr")[0].find_all(["th", "td"])
    headers_text = [cell.get_text(strip=True) for cell in header_cells]

    if "Song" in headers_text:
        table = t
        break

for row in table.select("tr")[1:]:
    song_cell = row.find("th")
    cols = row.find_all("td")

    if song_cell and len(cols) >= 3:
        song = song_cell.get_text(strip=True).replace('"', '')
        artist = cols[1].get_text(strip=True)
        streams = cols[2].get_text(strip=True)
        date = cols[3].get_text(strip=True).split("[")[0]
        scrape_time = datetime.now().isoformat()

        rows.append({
            "song": song,
            "artist": artist,
            "streams": streams,
            "date": date,
            "scrape_time": scrape_time
        })

df = pd.DataFrame(rows)

import os

filename = "spotify_streams.csv"

if os.path.exists(filename):
    # bestand bestaat → voeg nieuwe data toe
    df.to_csv(filename, mode="a", header=False, index=False)
else:
    # eerste keer → maak bestand met headers
    df.to_csv(filename, index=False)

print(f"Appended {len(df)} rows — dataset groeit met history")
df

print(f"Columns: {list(df.columns)}")
print(f"Data types:\n{df.dtypes}")
print(f"\nFirst 3 rows:")
df.head(3)

df["streams"] = (
    df["streams"]
      .str.replace(r"[^0-9.]", "", regex=True)
      .astype(float)
      * 1_000_000_000
)

df

print(df["streams"].dtype)

# Final check
print(f"Rows: {len(df)}")
print(f"Columns: {list(df.columns)}")
print(f"Data types:\n{df.dtypes}")
print(f"\nSample:")
df.head()


from supabase import create_client
from datetime import datetime

SUPABASE_URL = "https://jybykvzxyuimzsdnelys.supabase.co"
SUPABASE_KEY = "sb_publishable_shOYaNv5Db2ff1OL5SBD2g_uKVGZP0N"

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)

scrape_time = datetime.now().isoformat()

rows = []
for _, row in df.iterrows():
    rows.append({
        "song":       str(row.get("song", "")),
        "artist":     str(row.get("artist", "")),
        "streams":    float(row.get("streams", 0)),
        "date":       str(row.get("date", "")),
        "scraped_at": scrape_time,
    })

result = supabase.table("spotify_streams").insert(rows).execute()
print(f"✅ Inserted {len(rows)} rows into Supabase")